/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsScreenTransitionsRouteImport } from './routes/projects.screen-transitions'
import { Route as ProjectsOakRouteImport } from './routes/projects.oak'
import { Route as ProjectsGroundedRouteImport } from './routes/projects.grounded'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsScreenTransitionsRoute =
  ProjectsScreenTransitionsRouteImport.update({
    id: '/projects/screen-transitions',
    path: '/projects/screen-transitions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsOakRoute = ProjectsOakRouteImport.update({
  id: '/projects/oak',
  path: '/projects/oak',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsGroundedRoute = ProjectsGroundedRouteImport.update({
  id: '/projects/grounded',
  path: '/projects/grounded',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/grounded': typeof ProjectsGroundedRoute
  '/projects/oak': typeof ProjectsOakRoute
  '/projects/screen-transitions': typeof ProjectsScreenTransitionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/grounded': typeof ProjectsGroundedRoute
  '/projects/oak': typeof ProjectsOakRoute
  '/projects/screen-transitions': typeof ProjectsScreenTransitionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/grounded': typeof ProjectsGroundedRoute
  '/projects/oak': typeof ProjectsOakRoute
  '/projects/screen-transitions': typeof ProjectsScreenTransitionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/grounded'
    | '/projects/oak'
    | '/projects/screen-transitions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects/grounded'
    | '/projects/oak'
    | '/projects/screen-transitions'
  id:
    | '__root__'
    | '/'
    | '/projects/grounded'
    | '/projects/oak'
    | '/projects/screen-transitions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsGroundedRoute: typeof ProjectsGroundedRoute
  ProjectsOakRoute: typeof ProjectsOakRoute
  ProjectsScreenTransitionsRoute: typeof ProjectsScreenTransitionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/screen-transitions': {
      id: '/projects/screen-transitions'
      path: '/projects/screen-transitions'
      fullPath: '/projects/screen-transitions'
      preLoaderRoute: typeof ProjectsScreenTransitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/oak': {
      id: '/projects/oak'
      path: '/projects/oak'
      fullPath: '/projects/oak'
      preLoaderRoute: typeof ProjectsOakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/grounded': {
      id: '/projects/grounded'
      path: '/projects/grounded'
      fullPath: '/projects/grounded'
      preLoaderRoute: typeof ProjectsGroundedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsGroundedRoute: ProjectsGroundedRoute,
  ProjectsOakRoute: ProjectsOakRoute,
  ProjectsScreenTransitionsRoute: ProjectsScreenTransitionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
